
#ifndef UNBUCKLE_ERR_H
#define UNBUCKLE_ERR_H

#define EUBKEYNOTFOUND 	0x01
#define EUBOUTOFMEM 	0x02

#define PROC_UDP_INVALID	0x0
#define PROC_UDP_VALID		0x1
#define PROT_UNSUPPORTED	0x2

#define MEMCACHE_PROT_ERROR 	0x4
#define MEMCACHE_UNSUPPORTED_CMD	0x8
#define MEMCACHE_NO_KEY_SUPPLIED	0x16
#define MEMCACHE_PROT_OK	0x32

#endif
